load_limit = ["inf"]
query_path = "./dnsdebug/noerror.txt"
control_plane_nodes = 3
network_type = ["OpenShiftSDN", "OVNKubernetes"]
transport_mode = ["udp", "tcp"]
client_threads = [1]
distributed_computing_platform = "aws"

