dns_software_name = "coredns"
dns_software_version = "1.8.1"
openshift_cluster_version = "4.8.0-0.nightly-2021-06-19-005119"
kubernetes_cluster_version = "v1.21.0-rc.0+120883f"
control_plane_node_quantity = 3
data_plane_node_quantity = 3
load_limit = ["inf"]
query_path = ["./dnsdebug/noerror.txt", "./dnsdebug/nxdomain.txt"]
network_type = ["OpenShiftSDN", "OVNKubernetes"]
transport_mode = ["udp", "tcp"]
client_threads = [1,2,3,4,5,6,7,8]
distributed_computing_platform = "aws"
runtime_length = 90
timeout_length = 30